[package]
name = "kyne_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "See README.md in this directory."

[[bin]]
name = "kyne"
path = "src/main.rs"

[dependencies]
kyne_driver = { path = "../driver" }
kyne_formatter = { path = "../../tools/formatter" }
kyne_diagnostics = { path = "../diagnostics" }

[dev-dependencies]
kyne_cst = { path = "../cst" }
