//! Project scaffolding for `kyne new`/`kyne init`, per
//! docs/TOOLCHAIN.md §4 (Project Layout), §5 (`Kyne.toml`), and §6
//! (Project Templates).
//!
//! Pure filesystem generation - no compiler library is involved, per
//! §9's `kyne new`/`kyne init` entries ("Interaction with the compiler:
//! None").

use std::fs;
use std::io;
use std::path::Path;

pub struct Template {
    pub name: &'static str,
    pub description: &'static str,
    pub contract_source: &'static str,
}

const NFT_SOURCE: &str = include_str!("templates/nft.kyn");
const ORACLE_SOURCE: &str = include_str!("templates/oracle.kyn");

/// `hello` and `token` MUST use the Counter and Token contracts from
/// LANGUAGE_SPEC.md §16 verbatim, per §6 - `examples/canonical/` already
/// holds byte-identical copies of those blocks.
pub const TEMPLATES: &[Template] = &[
    Template {
        name: "hello",
        description: "minimal counter contract",
        contract_source: include_str!("../../../examples/canonical/counter.kyn"),
    },
    Template {
        name: "token",
        description: "fungible token contract",
        contract_source: include_str!("../../../examples/canonical/token.kyn"),
    },
    Template {
        name: "nft",
        description: "non-fungible token contract",
        contract_source: NFT_SOURCE,
    },
    Template {
        name: "oracle",
        description: "price-oracle contract",
        contract_source: ORACLE_SOURCE,
    },
];

pub fn find_template(name: &str) -> Option<&'static Template> {
    TEMPLATES.iter().find(|t| t.name == name)
}

/// Creates the full project skeleton, per §4's Project Layout table:
/// `Kyne.toml`, `src/contract.kyn`, empty `tests/` and `docs/`
/// directories, and a `.gitignore` excluding the tool-owned `build/` and
/// `.kyn/` directories (neither of which is created here - they are
/// generated by later commands, per §4's "Generated versus user-owned"
/// note).
pub fn scaffold(dir: &Path, package_name: &str, template: &Template) -> io::Result<()> {
    fs::create_dir_all(dir.join("src"))?;
    fs::create_dir_all(dir.join("tests"))?;
    fs::create_dir_all(dir.join("docs"))?;
    fs::write(dir.join("Kyne.toml"), kyne_toml(package_name, template))?;
    fs::write(
        dir.join("src").join("contract.kyn"),
        template.contract_source,
    )?;
    fs::write(dir.join(".gitignore"), "build/\n.kyn/\n")?;
    Ok(())
}

fn kyne_toml(name: &str, template: &Template) -> String {
    format!(
        "[package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"v1\"\n\
         authors = []\n\
         description = \"A {desc}, generated by `kyne new --template {tpl}`.\"\n\
         \n\
         [build]\n\
         \n\
         [dependencies]\n",
        desc = template.description,
        tpl = template.name,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_template_contract_parses_cleanly() {
        for template in TEMPLATES {
            let (_, diagnostics) = kyne_cst::Cst::parse(template.contract_source, "contract.kyn");
            assert!(
                diagnostics.is_empty(),
                "template `{}` does not parse cleanly: {diagnostics:?}",
                template.name
            );
        }
    }

    #[test]
    fn every_template_contract_is_already_canonically_formatted() {
        for template in TEMPLATES {
            let formatted = kyne_formatter::format(template.contract_source)
                .unwrap_or_else(|d| panic!("template `{}` failed to format: {d:?}", template.name));
            assert_eq!(
                formatted, template.contract_source,
                "template `{}` is not canonically formatted",
                template.name
            );
        }
    }

    #[test]
    fn find_template_is_case_sensitive_and_total() {
        assert!(find_template("hello").is_some());
        assert!(find_template("token").is_some());
        assert!(find_template("nft").is_some());
        assert!(find_template("oracle").is_some());
        assert!(find_template("Hello").is_none());
        assert!(find_template("nonexistent").is_none());
    }

    #[test]
    fn kyne_toml_is_valid_looking_and_names_the_package() {
        let toml = kyne_toml("my-token", &TEMPLATES[1]);
        assert!(toml.contains("name = \"my-token\""));
        assert!(toml.contains("edition = \"v1\""));
    }
}
